name: 自动双源无损强行合并-备用线

on:
  schedule:
    - cron: '43 0,12 * * *'
  workflow_dispatch: 

# 🌟 显式强制赋予工作流最高写权限，彻底杜绝 128 推送报错
permissions: write-all

jobs:
  fetch-and-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Fetch target files
      run: |
        mkdir -p datas
        curl -L "https://cnb.cool/fish201/xs/-/git/raw/main/api.json" -o datas/cnb.json
        curl -L "https://raw.githubusercontent.com/FGBLH/HKL/refs/heads/main/ok%E6%B5%B7%E8%B1%9A.json" -o datas/haitun.json
        curl -L "https://gh-proxy.com/https://raw.githubusercontent.com/ediart/tvbox/refs/heads/main/lz/py.json" -o datas/lz.json

    # 🛠️ 严格前置运行合并脚本，由 Python 直连驱动双通道分流、高精度比对与 TG 发射
    - name: Text Merge JSON and Send TG Notice
      env:
        # 把密钥安全传给 Python 核心去直发
        TG_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python modify_config.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global core.quotepath false
        
        # 确保把生成的全量版、纯净版动态 JSON 实体以及容灾备份文件一并安全推送到仓库
        git add datas/
        if ! git diff --cached --exit-code --quiet; then
          git commit -m "双源自适应硬核合并 (蝴蝶影视全量/纯净双矩阵系列 & 容灾备份系统): $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:${{ github.ref_name }}
        else
          echo "文件内容没有发生实际变化，无需更新，优雅退出。"
        fi
