name: 自动双源无损强行合并-备用线

on:
  schedule:
    - cron: '43 0,12 * * *'
  workflow_dispatch: 

permissions: write-all

jobs:
  fetch-and-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Fetch target files
      run: |
        mkdir -p datas
        curl -L "https://cnb.cool/fish2018/xs/-/git/raw/main/api.json" -o datas/cnb.json
        curl -L "https://raw.githubusercontent.com/FGBLH/HKL/refs/heads/main/ok%E6%B5%B7%E8%B1%9A.json" -o datas/haitun.json
        curl -L "https://gh-proxy.com/https://raw.githubusercontent.com/ediart/tvbox/refs/heads/main/lz/py.json" -o datas/lz.json

    - name: Text Merge JSON and Send TG Notice
      env:
        TG_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        # 跑你仓库里对应的这个 modify_config.py 脚本
        python modify_config.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global core.quotepath false
        
        git add datas/
        if ! git diff --cached --exit-code --quiet; then
          git commit -m "双源自适应矩阵合并 (老杨TV全量版 & 客厅纯净版双版本): $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:${{ github.ref_name }}
        else
          echo "文件内容没有发生实际变化，无需更新，优雅退出。"
        fi
